### ISSUE TITLE
Remove ads

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/stackedit#1]
Would it be possible to disable/remove the following?:
- the "StackEdit 4 is out"/tutorial bobble when opening StackEdit the first time
- the `> Written with [StackEdit](https://stackedit.io/).` when making a new document
- all the pink boxes that says `Please consider sponsoring StackEdit for $5/year (or sign in if you're already a sponsor).` in all the modals
- all the `Try Classeur beta!` in all the modals

The following is not really an ad, but a modal that is annoying =)
- remove the modal that appears when clicking Save to CouchDB

**Comment by iainbryson** [comment]
I think this is done.
