### ISSUE TITLE
Move docker-stackedit/* to here

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/stackedit#11]
The few files in docker-stackedit should be moved to this repo except for the `LICENSE` file.

After the change docker-stackedit shouldn't be used for anything.

**Comment by iainbryson** [comment]
I think this is already done.  The file contents are different of course, but the Dockerfile and other pieces from docker-stackedit have already been moved.  docker-stackedit isn’t used for anything anymore IIRC.

**Comment by dtu-compute** [comment]
Perfect. I have now made docker-stackedit private and will delete it in a months time or so.
