### ISSUE TITLE
Get couchdb to work again

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/stackedit#13]
After updating the certs, stackedit couldn't connect to couchdb:6984 and couchdb couldn't write its db files any more. So I have created a new `fedora` branch in couchdb which we should use/merge to devel/2016. This one uses port 5984.

The admin and password wasn't inserted by `generate.rb` so I made this fix. https://github.com/dtu-compute/dtu-enote/commit/22bb55ae5408422010b4ac13d2bfac755b6e7c5e

Looking in `/vol/log/couchdb.log` I see
```
[Sat, 24 Dec 2016 14:22:43 GMT] [debug] [<0.270.0>] httpd 401 error response:
 {"error":"unauthorized","reason":"You are not a server admin."}
```

**Comment by dtu-compute** [comment]
The workaround didn't fix the issue all the way. `config-dtu.js` have `couchdb:6984` hardcoded and even updating it, leaves an issue with couchdb:
```
[Wed, 21 Dec 2016 23:53:23 GMT] [info] [<0.32.0>] Apache CouchDB has started on http://0.0.0.0:5984/
[Wed, 21 Dec 2016 23:53:26 GMT] [info] [<0.107.0>] 172.18.0.23 - - GET / 200
[Wed, 21 Dec 2016 23:53:36 GMT] [info] [<0.148.0>] 172.18.0.22 - - PUT /_config/admins/dtuadmin 401
[Wed, 21 Dec 2016 23:53:36 GMT] [info] [<0.106.0>] 172.18.0.22 - - PUT /_config/admins/user02417 401
[Wed, 21 Dec 2016 23:53:36 GMT] [info] [<0.105.0>] 172.18.0.22 - - PUT /db02417 401
[Wed, 21 Dec 2016 23:53:36 GMT] [error] [<0.164.0>] Could not open file /usr/local/var/lib/couchdb/db02417.couch: no such file or directory
[Wed, 21 Dec 2016 23:53:36 GMT] [info] [<0.104.0>] 172.18.0.22 - - GET /db02417/_design/validate 404
[Wed, 21 Dec 2016 23:53:36 GMT] [error] [<0.168.0>] Could not open file /usr/local/var/lib/couchdb/db02417.couch: no such file or directory
[Wed, 21 Dec 2016 23:53:36 GMT] [info] [<0.103.0>] 172.18.0.22 - - PUT /db02417/_design/validate 404
```

So I have created a new `fedora` branch in couchdb which we should use/merge to devel/2016.

**Comment by iainbryson** [comment]
This should be fixed now.  I've deployed to devel2 for staging.
