### ISSUE TITLE
Fedora 24 (and I assume 25) requires a redesign of confi-dtu.js

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/stackedit#14]
I noticed this when working on the Web site bugs.  When I moved stackedit to Fedora 24, this caused nodejs' version to bump from v0.10.42 to v4.7.2 , which broken runsync, upon which our configure scripts depend.  In addition to making the cmd.sh script bail on this error, I'll need to fix this (move to spawn?) when moving to Fedora 25.

**Comment by dtu-compute** [comment]
Ok, let's keep it at fedora 23.

**Comment by iainbryson** [comment]
Fixed (already had the pieces in place)
