### ISSUE TITLE
Upsteam basic auth for CouchDB

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/stackedit#3]
Before the basic auth code is upstreamed it would be great to have a check for `users.yaml` in StackEdit, which would only enable CAS if this file is present. That way anyone can use the dtu-compute/stackedit fork.

When done, a link to dtu.compute/couchdb could be included as well for a turn key solution?

**Comment by iainbryson** [comment]
I'm not sure what this means:

> When done, a link to dtu.compute/couchdb could be included as well for a turn key solution?

Also: should there be a separate issue for updating `users.yaml` in realtime?  i.e. like the quiz?

**Comment by iainbryson** [comment]
Also: does `users.yml` replace the current stackedit.yml? Or is it a different file? I've been considering reusing the same file formats as quizzes, so having a courses.yml and then various users files separate, with he couchdb urls either in the `courses.yml` or as a separate config file.

**Comment by dtu-compute** [comment]
> When done, a link to dtu.compute/couchdb could be included as well for a turn key solution?

Here I were thinking that the StackEdit patch alone would perhaps not be so useful without also knowing how CouchDB should be configured? So perhaps it would make sense to link to ours, so they can see how it should look to get your patch working?

> Also: should there be a separate issue for updating users.yaml in realtime? i.e. like the quiz?

Here is mixed up `stackedit.yaml` and `users.yaml` =)

It would be a nice to have feature for StackEdit not having to reload it when updating `stackedit.yaml`, but not important I would say. The file will change maybe once per year, and no live users will be affected by it. So I'd if it is easy, then let's do it as part of the dtuquiz 2017 version.

> Also: does `users.yml` replace the current stackedit.yml? Or is it a different file?

It is the same. I mixed up file names =)

> I've been considering reusing the same file formats as quizzes, so having a courses.yml and then various users files separate, with he couchdb urls either in the `courses.yml` or as a separate config file.

That is a great idea!!

To complicate things a bit more, then there also is `users.yaml` (this time not mixed up=) ) in

https://github.com/dtu-compute/docker-askbot/blob/devel/users.yaml

Could that one also be standardized?

A note about `docker-askbot` (each course will have their own askbot). After logging in using the CAS login, it gets the redirection link wrong. I have contacted the developer, but perhaps you could look at it if I don't hear from him soon?

**Comment by dtu-compute** [comment]
He is not very active on StackEdit v1, so we should first make sure that he will pull the fix.

**Comment by dtu-compute** [comment]
Closing as I haven't heard from the StackEdit author.
