### ISSUE TITLE
Secret key in config file

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/stackedit#5]
https://github.com/dtu-compute/stackedit/blob/devel/app/index.js#L13

looks like something we should have in a config file. Perhaps in `/vol/config/stackedit.yaml`?

Or is it just for signing things, so it can be generated during Docker build?

**Comment by iainbryson** [comment]
Fixes.

**Comment by dtu-compute** [comment]
Ok, so it just is a session key. Then let's generate it either at Docker build or at run time.

If by build, the perhaps?:

```
r=$(od -vAn -N16 -tx < /dev/urandom | tr -d " ")
```
