### ISSUE TITLE
Put admin and pw in couchdb.yaml

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/stackedit#6]
https://github.com/dtu-compute/stackedit/blob/devel/config-dtu.js#L65

**Comment by dtu-compute** [comment]
`/vol/config/couchdb.yaml` on staging needs to be updated. With?:

```
'_admin':
  db: https://dtuadmin:Aevee7Le@couchdb:6984
```

Or?

**Comment by iainbryson** [comment]
Correct. I haven’t deployed yet though.
